export const FETCH_MOVIES = "FETCH_MOVIES";
export const RETURN_MOVIES = "RETURN_MOVIES";

export const FETCH_TVSHOWS = "FETCH_TVSHOWS";
export const RETURN_TVSHOWS = "RETURN_TVSHOWS";

export const FETCH_PEOPLE = "FETCH_PEOPLE";
export const RETURN_PEOPLE = "RETURN_PEOPLE";

export const FETCH_DISCOVER = "FETCH_DISCOVER";
export const RETURN_DISCOVER = "RETURN_DISCOVER";

export const FETCH_KEYWORDS = "FETCH_KEYWORDS";
export const RETURN_KEYWORDS = "RETURN_KEYWORDS";

export const FETCH_SEARCH = "FETCH_SEARCH";
export const RETURN_SEARCH = "RETURN_SEARCH";

export const FETCH_DETAILS = "FETCH_DETAILS";
export const RETURN_DETAILS = "RETURN_DETAILS";

export const FETCH_USER = "FETCH_USER";
export const RETURN_USER = "RETURN_USER";

export const RESET_STORE = "RESET_STORE";